# https://docs.docker.com/get-started/docker-concepts/building-images/multi-stage-builds/

# STEP 1 of multistage dockerfile build
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
# npm clean install so it wont look for stuff to update
RUN npm ci
COPY . .
RUN npm run build

#due to multistage, any time we build a new image, it reuses the installed stuff above if they have not changed
# code only changes will only invalidate the cache at line 9 so the npm wont install again

#step 2 final
FROM nginx:1.27-alpine as final
WORKDIR /app
EXPOSE 80
COPY --from=build /app/dist /usr/share/nginx/html
#take it from local dont take conf from the build
COPY nginx.conf /etc/nginx/conf.d/default.conf 