server {
    
    root /usr/share/nginx/html;
    index index.html;

    #https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#trying-several-options
    location / {
        try_files $uri /index.html;
    }
}